config/routes.rb
Reddit::Application.routes.draw do
  root to: "static_pages#home"

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :subs

  resources :links, except: [:index]
end

app/models/link.rb
class Link < ActiveRecord::Base

  attr_accessible :user_id, :title, :url, :body

  validates_presence_of :user_id, :title, :url

  belongs_to :user,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id

  has_many :linksubs,
  class_name: "LinkSub",
  foreign_key: :link_id,
  primary_key: :id

  has_many :subs, through: :linksubs, source: :sub

end

app/models/link_sub.rb
class LinkSub < ActiveRecord::Base

  attr_accessible :sub_id, :link_id

  validates_presence_of :sub_id, :link_id
  validates_uniqueness_of :sub_id, scope: :link_id

  belongs_to :link,
  class_name: "Link",
  foreign_key: :link_id,
  primary_key: :id

  belongs_to :sub,
  class_name: "Sub",
  foreign_key: :sub_id,
  primary_key: :id

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  attr_accessible :name, :user_id

  validates_uniqueness_of :name
  validates_presence_of :name, :user_id

  belongs_to :mod,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id

  has_many :linksubs,
  class_name: "LinkSub",
  foreign_key: :sub_id,
  primary_key: :id

  has_many :links, through: :linksubs, source: :link

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :user_name, :password

  attr_reader :password

  before_validation :ensure_session_token

  validates :user_name, :presence => true
  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }

  has_many :subs,
    class_name: "Sub",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy

  has_many :links,
    class_name: "Link",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy

  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)

    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.generate_session_token
      SecureRandom::urlsafe_base64(16)
    end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
  include LinksHelper
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # TODO ensure user is logged in before linking

  def show
    @link = Link.find(params[:id])
  end

  def new
    unless current_user
      flash[:errors] = ["You gotta sign in to link, brah!"]
      redirect_to new_session_url
    else
      @link = Link.new
    end
  end

  def create
    params[:link][:url] = url_with_protocol(params[:link][:url])
    @link = Link.new(params[:link])

    if @link.save!
      redirect_to link_url(@link)
    else
      flash[:errors] = @link.errors.full_messages
      redirect_to new_link_url
    end
  end

  def edit
    @link = Link.find(params[:id])
    @linksubs_string = @link.subs.map!{ |sub| sub.name }.join(" ")
    fail
  end

  def update
    @sub = Sub.find_by_id(params[:link][:url])

    unless @sub
      flash[:errors] = ["Subreddit doesn't exist"]
      render :edit
    else
      @link = Link.find(params[:id])

      if @link.update_attributes(params[:link])
        redirect_to sub_url(@sub)
      else
        flash[:errors] = @sub.errors.full_messages
        render :edit
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    login_user!
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil

    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def new
    @sub = Sub.new
    # TODO finish links and have: 3.times { @sub.links.build }
  end

  def create
    user_id = User.find_by_user_name(params[:sub][:user_name]).id
    @sub = Sub.new(name: params[:sub][:name], user_id: user_id)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    # TODO kill it with fire...figure out more elegant way to handle bad input
    if params[:sub][:name] == "" || params[:sub][:user_name] == ""
      flash[:errors] = ["You're fillin out the form wrong, brah!"]
      redirect_to edit_sub_url(Sub.find(params[:id]))
    elsif User.find_by_user_name(params[:sub][:user_name]).nil?
      flash[:errors] = ["That user doesn't exist!"]
      redirect_to edit_sub_url(Sub.find(params[:id]))
    else
      user_id = User.find_by_user_name(params[:sub][:user_name]).id
      @sub = Sub.find(user_id)
      if @sub.update_attributes(name: params[:sub][:name], user_id: user_id)
        redirect_to sub_url(@sub)
      else
        flash[:errors] = @sub.errors.full_messages
        render :edit
      end
    end
  end

  def destroy
    Sub.delete(params[:id])
    redirect_to subs_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      login_user!
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def url_with_protocol(url)
    /^http/.match(url) ? url : "http://#{url}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def login_user!
    user = User.find_by_credentials(
      params[:user][:user_name],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      user.reset_session_token!
      self.current_user = user
      redirect_to root_url
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if flash[:errors] && !flash[:errors].empty? %>
  <% flash[:errors].each do |error| %>
	 <%= error %> <br>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit-Clone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->
    </head>
    <body>
      <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="navbar-inner">
          <div class="container">
            <%= link_to "Reddit-Clone", '/', id: "logo" %>
            <nav>
              <ul class="nav pull-right">
                <li><%= link_to "Home", root_url %></li>
                <li><%= link_to "Subs", subs_url %>
                <% if current_user %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <%= current_user.user_name %>
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", user_url(current_user), method: :get %>
                      <li><%= link_to "Log out", '/session/', method: :delete%></li><%# TODO change to button_to %>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Sign in", '/session/new' %></li>
                <% end %>
              </ul>
            </nav>
      </header>
      <div class="container">
        <%= yield %>
        <footer class="footer">
          <small>
            <a href="/">Reddit-Clone</a>
            by Yours Truely
          </small>
          <nav>
            <ul>
              <li><%= link_to "Help", root_url %></li>
              <li><%= link_to "Legal", root_url %></li>
              <li><%= link_to "Contact", root_url %></li>
              <li><%= link_to "Issues",   'https://github.com/jclif/reddit-clone/issues' %></li>
            </ul>
          </nav>
        </footer>
      </div>
    </div>
    </body>
  </html>

app/views/links/_form.html.erb
<% action = (link.persisted? ? link_url(link) : links_url) %>
<% method = (link.persisted? ? "put" : "post") %>
<% message = (link.persisted? ? "Update link" : "Add link") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

    <label for="link_title">Title</label>
    <input
       id="link_title"
       name="link[title]"
       type="text"
       value=<%= link.title.to_s %>>
    <br>
    <input
       id="link_user_id"
       name="link[user_id]"
       type="hidden"
       value=<%= current_user.id.to_s %>>
    <br>
    <label for="link_name">Body</label>
    <input
       id="link_body"
       name="link[body]"
       type="text"
       value=<%= link.body.to_s %>>
    <br>
    <label for="link_url">URL</label>
    <input
       id="link_url"
       name="link[url]"
       type="text"
       value=<%= link.url.to_s %>>
    <br>
    <label for="link_subs">Subreddits</label>
    <input
       id="link_subs"
       name="link[subs]"
       type="text"
       value=<%= link.url.to_s %>>
    <br>



  <input type="submit" value="<%= message %>">
</form>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render :partial => "layouts/errors" %>

<%= render "form", link: @link %>

app/views/links/new.html.erb
<h1>Post a Link!</h1>

<%= render :partial => "layouts/errors" %>

<%= render "form", link: @link %>

app/views/links/show.html.erb
<h1><a href=<%= @link.url %>><%= @link.title %></a></h1>
<p>Posted by <%= link_to "#{@link.user.user_name}", user_url(@link.user) %> @ <%= @link.created_at %>
<p>Body: <%= @link.body %>

<% if current_user && current_user.id == @link.user_id %>
  <%= button_to "Edit", edit_link_url(@link), method: :get, class: "btn btn-small" %>
  <%= button_to 'Destroy', link_url(@link),
              :confirm => 'Are you sure?!', :method => :delete, class: "btn btn-small" %>
<% end %>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to reddit-clone</h1>

  <h2>
    Waste your time, or get out! <br>Why productive when you can not productive?<br> Look at all these <a href=<%= subs_url %>>subreddits (clones)!!!</a> Click on them now.
  </h2>

  <% unless current_user%>
    <%= link_to "Sign up!", new_user_url, class: "btn btn-large btn-primary" %>
  <% end %>
  <h2><%= link_to "Link everything now!", new_link_url %></h2>
</div>

app/views/subs/_form.html.erb
<% action = (sub.persisted? ? sub_url(sub) : subs_url) %>
<% method = (sub.persisted? ? "put" : "post") %>
<% message = (sub.persisted? ? "Update sub" : "Add sub") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <% if method == "post" %>
    <label for="sub_name">Name</label>
    <input
       id="sub_name"
       name="sub[name]"
       type="text">
    <br>
    <input
       id="sub_user_name"
       name="sub[user_name]"
       type="hidden"
       value=<%= current_user.user_name %>>
    <br>
  <% else %>
    <label for="sub_name">Name</label>
    <input
       id="sub_name"
       name="sub[name]"
       type="text"
       value=<%= sub.name %>>
    <br>
    <label for="sub_user_id">Mod Username</label>
    <input
       id="sub_user_name"
       name="sub[user_name]"
       type="text"
       value=<%= current_user.user_name %>>
    <br>
  <% end %>

  <input type="submit" value="<%= message %>">
</form>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render :partial => "layouts/errors" %>

<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>Subs</h1>

<% if current_user %>
  <%= button_to "Add Sub", new_sub_url, method: :get, class: "btn btn-small" %>
<% end %><br>

<% @subs.each do |sub| %>
  <h3> <%= link_to "#{sub.name}", sub_url(sub) %> </h3><br>
<% end %>

app/views/subs/new.html.erb
<h1>Make a Sub!</h1>

<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>

<% @sub.links.each do |link| %>
  <%= link_to "#{p link.inspect}", link_url(link) %><br>
<% end %>

<% if current_user && current_user.id == @sub.user_id %>
  <%= button_to "Edit", edit_sub_url(@sub), method: :get, class: "btn btn-small" %>
  <%= button_to 'Destroy', sub_url(@sub),
              :confirm => 'Are you sure?!', :method => :delete, class: "btn btn-small" %>
<% end %>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update Yoself" : "Create Yoself") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[user_name]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>" class= "btn btn-small" >
</form>

app/views/users/new.html.erb
<h1>Sign up plz!</h1>

<%= render :partial => "layouts/errors" %>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1><%= @user.user_name%></h1>
<br>

<img src="/assets/default_pic.png" width="200">

<br>
<hr>
<br>

<h2>Links</h2>
<% @user.links.each do |link| %>
  <%= link_to "#{p link.inspect}", link_url(link) %><br>
<% end %>

<hr>

<h2>Subreddits Modded</h2>
<% @user.subs.each do |sub| %>
  <%= link_to "#{sub.name}", sub_url(sub) %><br>
<% end %>